### ISSUE TITLE
Support both phones and desktop

### ISSUE THREAD

**Issue by marcnormandin** [marcnormandin/pso_js#11]
It is fun to run the app on my phone, but it doesn't display efficiently on it. It needs a new layout.

**Comment by marcnormandin** [comment]
The way that both phones and desktop are supported is that the main design of the demo page is laid out linearly. The code checks for the width and height of the window, and then selects the minimum as the dimensions of the SVG plot square. It scales that size to 90 percent to make it look nicer. The demo works well on the phone and desktop now, so I am closing this commit.

Implemented in commit ececee3e30386da4a43f01bb32c9fe92ff5f2b57.

**Comment by martinberoiz** [comment]
is there any tutorial for this? I'm interested

**Comment by marcnormandin** [comment]
Tutorial for using the PSO demo or for the resizing using javascript?

**Comment by martinberoiz** [comment]
tutorial for support for phones and desktop

**Comment by martinberoiz** [comment]
I just found [this](http://gridstylesheets.org/demos/hello-world/) for layout interfaces. It can help positioning objects relative to each other. I leave it here in case you're interested. It's a javascript.

**Comment by marcnormandin** [comment]
Okay, thanks.

On Sun, Jun 7, 2015 at 9:08 AM, Martin Beroiz notifications@github.com
wrote:

> I just found this http://gridstylesheets.org/demos/hello-world/ for
> layout interfaces. It can help positioning objects relative to each other.
> I leave it here in case you're interested. It's a javascript.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/marcnormandin/pso_js/issues/11#issuecomment-109759152
> .

## 

Marc E. Normandin
Graduate Student
Dept. of Physics and Astronomy &
Center for Gravitational Wave Astronomy,
University of Texas at Brownsville.
University of Texas at San Antonio
Voice: +1 (956) 433-3251
