### ISSUE TITLE
Feature: Add particle tracks

### ISSUE THREAD

**Issue by martinberoiz** [marcnormandin/pso_js#8]
You could show the particles tracks over the map, or even uncover the map as the particles transverse it.
(Congrats on the new design, btw, it looks much better)

**Comment by marcnormandin** [comment]
That is my idea I told you about yesterday! :)

On Thu, May 28, 2015 at 3:25 PM, Martin Beroiz notifications@github.com
wrote:

> You could show the particles tracks over the map, or even uncover the map
> as the particles transverse it.
> (Congrats on the new design, btw, it looks much better)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/marcnormandin/pso_js/issues/8.

## 

Marc E. Normandin
Graduate Student
Dept. of Physics and Astronomy &
Center for Gravitational Wave Astronomy,
University of Texas at Brownsville.
University of Texas at San Antonio
Voice: +1 (956) 433-3251

**Comment by martinberoiz** [comment]
let this issue be a reminder so you don't forget ;)

**Comment by marcnormandin** [comment]
This is a wonderful new feature. Implemented.
